### ISSUE TITLE
Investigate deployment options

### ISSUE THREAD

**Issue by andykitch** [icipe-official/vectoratlas-software-code#45]
There are multiple options for deployment:
 - Docker-compose containers in Ubuntu machine on Azure
 - Single container in Azure App Service
 - On a physical machine at the University
The feasibility of these needs to be investigated, including related costs and long-term maintainability. 

**Acceptance criteria**:
- [x] The results of this investigation should be documented on the story
- [x] An ADR for the decision should be added to the ADRs
- [x] Any resulting stories should be added to the backlog.

**Comment by ray-millward-tessella** [comment]
## Investigation
The initial part of the investigation looked at the technology options:

**Multi-container support**
Multi-container support with an individual Azure App Service is possible but still in preview (https://docs.microsoft.com/en-us/azure/app-service/tutorial-multi-container-app) and therefore not recommended without risk at this time. It is potentially a cost effective mechanism at **£720/year** but this would depend on whether it is used alongside a managed database. Note we wouldn't be able to connect directly to the container stack to take back ups and we'd hae to working out what the logging and debugging process would be.

**Host in Kubernetes**
The docker compose stack could be encapsulated within a Kubernetes pod and run as part of a Kubernetes cluster. This would allow compute costs to be shared across many different apps and make the most efficient use of resources. There isn't an existing Kubernetes cluster at either Oxford or ICIPE and so this isn't an option for now - using Kubernetes only works if there are many applications sharing the hardware and the cost.

**Azure virtual machine with managed database**
An Azure virtual machine could be used to host the docker-compose stack, potentially with or without a managed postgres database. A D4a machine with 4 CPUs, 16GB RAM in South Africa North would cost **£1850/year** (alternatively a D2a v4 would be £940/year if an external database is used). A managed postgres instance with 50GB of data would be **£870/year**

There is an option to reserve machines for 3 years which significantly reduces the cost, the D4a machine would come down to £720/year and the D2a would be £360/year.

There would also be additional costs around Azure storage for hosting some small amounts of data as well as the costs of public IPs and networking but these should all be minor.

**Virtual machine within the Oxford data centre**
The University of Oxford provides an internal data centre for projects to use where at the moment a 4 CPU, 4GB RAM costs **£350/year**.

Additionally there is the ability to get 1TB of storage for a one off cost of £350 to the project.

## Recommendation
Initally we should aim to provsion a compute environment in Oxford so we can validate that a single machine is enough (potentially whether a smaller machine would be sufficient). This has the lowest cost to the project while we determine what the appropriate long-term support would be.

As support transitions to ICIPE we would then look to deploy the production environment in to Azure and we would have more confidence in the specifications in order to make best use of the reservation prices.

**Comment by ray-millward-tessella** [comment]
After discussions with Oxford IT, the original plan is more difficult than expected as it requires having an account at Oxford in order to then connect to the network. Given that the system will eventually be moving to Azure anyway, we have made the choice to deploy the test environment there as well.

The specs for the environments are currently:

### Test environment:
Region: South Africa North (to help reduce latency)
Virtual Machine: Linux Ubuntu (Standard Tier) B4ms - 4 Cores, 16GB RAM, 32GB temporary storage ($92.67/month with 1 yr reservation)
Azure Database for PostgreSQL: Single server, Basic tier, Gen 5 2 vCore,  50 GB storage, LRS backup with 100GB storage ($86.60/month)
1 static IP address ($2.63/month)
We'll also need a small amount of blob storage to store the overlay maps and mbtiles files - 10GB max (approx $5/month)

**Total: $186.95/month - $2243.40/yr**

### Prod environment (provisional):
Same as test environment but with a bigger virtual machine on a 3 yr reservation
Virtual Machine: Linux Ubuntu (Standard Tier) B8ms - 8 Cores, 32GB RAM, 64GB temporary storage ($119.11/month with 3 yr reservation)

**Total: $213.39/month - $2560.68/yr**

We need to confirm that the resources are sufficient for the production environment before booking a 3 yr reservation.

**Comment by ray-millward-tessella** [comment]
The team at ICIPE are working through provisioning the test environment currently.

**Comment by ray-millward-tessella** [comment]
@andykitch can you review the output of this investigation please so we can move it to testing.

New stories #64 and #65 created from this investigation.

**Comment by andykitch** [comment]
Happy with the output - I'll move to testing when the ADR has been written.

**Comment by ray-millward-tessella** [comment]
ADR added for the decision to deploy to Azure.

**Comment by ray-millward-tessella** [comment]
Story #64 created from the decision
